import type { Metadata } from "next";
import "../styles/globals.css";
import Providers from "@/components/layout-prov";

import ThemeProvider from "@/components/themes/theme-provider";

import { fontVariables } from "@/components/themes/font.config"
import { cn } from '@/lib/utils';
const META_THEME_COLORS = {
  light: "#ffffff",
  dark: "#09090b",
};
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                if (localStorage.theme === 'dark' || ((!('theme' in localStorage) || localStorage.theme === 'system') && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.querySelector('meta[name="theme-color"]').setAttribute('content', '${META_THEME_COLORS.dark}')
                }
              } catch (_) {}
            `,
          }}
        />
      </head>
      <body
        className={cn(
          "bg-background  font-sans antialiased",
          fontVariables,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
          enableColorScheme
        >
          <Providers activeThemeValue="mono">{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
