import type { Metadata } from "next";
import "../styles/globals.css";

import {ThemeProvider} from "@/components/theme-provider";
import { ActiveThemeProvider } from "@/components/themes/active-theme";

import { fontVariables } from "@/components/themes/font.config"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={fontVariables}>
      <body className="antialiased">
        {/* 1️⃣ next-themes (dark / system) */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* 2️⃣ your theme system (claude, vercel, mono…) */}
          <ActiveThemeProvider>{children}</ActiveThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
